### ISSUE TITLE
Are you accepting contributions to this project? 

### ISSUE THREAD

**Issue by raunakhajela** [iamsatyajit05/GitHub-Profile-Page-Creator#1]

**Comment by iamsatyajit05** [comment]
Yeah brother, On project website you can see support with crypto coffee option. 

And if you want to support with currency then I can give you the my GPay Number.

And thanks you giving me the reminder to the qdd that option also 😊

**Comment by hellosatyajit** [comment]
Yeah brother, On project website you can see support with crypto coffee option.

And if you want to support with currency then I can give you the my GPay Number.

And thanks you giving me the reminder to the qdd that option also 😊

**Comment by raunakhajela** [comment]
I am not talking about contributions with money. I am talking about code contributions.

**Comment by hellosatyajit** [comment]
My Bad 😅

Yes, you can contribute to this project, so this project can become even better.
